[workspace]
resolver = "2"

members = ["day-*"]

[workspace.dependencies]
itertools = "0.12.0"
criterion = "0.5.1"
rstest = "0.18.2"
indoc = "2.0.4"
regex = "1.10.3"
colored = "2.1.0"

[profile.flamegraph]
inherits = "release"
debug = true
